name: Deploy Docker to EC2

on:
 workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Build and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@<EC2_PUBLIC_IP> << 'EOF'
          # Update and install Docker if not already installed
          sudo apt-get update
          sudo apt-get install -y docker.io
          
          # Navigate to the project directory
          cd /path/to/your/project

          # Build the Docker image
          sudo docker build -t my-app .

          # Run the Docker container
          sudo docker run -d -p 80:80 my-app
        EOF
